### PR TITLE
renamed /help to /ezpr help & /ezpr to /ezpr submit

### PR DESCRIPTION
**Pull request by Rishav1707**
## [EZPR-33] feature enhancement: rename /help --> /ezpr help & /ezpr --> /ezpr submit

Fixes: #33 

### Changes
- Renamed `/help --> /ezpr help` & `/ezpr --> /ezpr submit`.

### CODE REVIEW

**Comment by jcserv** [comment]
Hey @Rishav1707, appreciate the contribution. 

Apologies for not providing more detail, but the issue was intended to rename the slack commands so that users would input `/ezpr help` to receive a message with help instructions and `/ezpr submit` to submit pull review requests, and not update file names.

Let me know if you'd like to give that a go, otherwise I can close this PR.

**Comment by Rishav1707** [comment]
> Hey @Rishav1707, appreciate the contribution.
> 
> Apologies for not providing more detail, but the issue was intended to rename the slack commands so that users would input `/ezpr help` to receive a message with help instructions and `/ezpr submit` to submit pull review requests, and not update file names.
> 
> Let me know if you'd like to give that a go, otherwise I can close this PR.

How to rename slack commands and from where?

**Comment by Rishav1707** [comment]
> > Hey @Rishav1707, appreciate the contribution.
> > Apologies for not providing more detail, but the issue was intended to rename the slack commands so that users would input `/ezpr help` to receive a message with help instructions and `/ezpr submit` to submit pull review requests, and not update file names.
> > Let me know if you'd like to give that a go, otherwise I can close this PR.
> 
> How to rename slack commands and from where?

Can you please help me...😊

**Comment by jcserv** [comment]
Hey @Rishav1707, Slack commands are configured via the manifest.yml (https://api.slack.com/reference/manifests). The command handlers will also need to be updated (in app.ts)

I've added some docs around locally running so highly recommend you check that out so that you can test it after your changes are made.

**Comment by Rishav1707** [comment]
> Hey @Rishav1707, Slack commands are configured via the manifest.yml (https://api.slack.com/reference/manifests). The command handlers will also need to be updated (in app.ts)
> 
> I've added some docs around locally running so highly recommend you check that out so that you can test it after your changes are made.

Ok I am creating another PR for this issue #33

**Pull request closed without merging**
