### PR TITLE
Slash commands changed

### PR DESCRIPTION
**Pull request by Rishav1707**
## [EZPR-33] feature enhancement: rename /help --> /ezpr help & /ezpr --> /ezpr submit

Fixes: #33

### Changes

- Slash commands changed

### CODE REVIEW

**Comment by jcserv** [comment]
Hey @Rishav1707, did you verify this works?
Could you please post screenshots/recordings?

**Comment by Rishav1707** [comment]
> Hey @Rishav1707, did you verify this works? Could you please post screenshots/recordings?

How to verify?

**Comment by Rishav1707** [comment]
> Hey @Rishav1707, did you verify this works? Could you please post screenshots/recordings?

How to verify?

**Comment by Rishav1707** [comment]
> > Hey @Rishav1707, did you verify this works? Could you please post screenshots/recordings?
> 
> How to verify?

?? @jcserv

**Comment by jcserv** [comment]
> > > Hey @Rishav1707, did you verify this works? Could you please post screenshots/recordings?
> > 
> > 
> > How to verify?
> 
> ?? @jcserv



> > > Hey @Rishav1707, did you verify this works? Could you please post screenshots/recordings?
> > 
> > 
> > How to verify?
> 
> ?? @jcserv

Check out https://github.com/jcserv/ez-pr-bot/blob/main/docs/setup.md or https://slack.com/help/articles/115005265703-Create-a-bot-for-your-workspace

**Pull request closed without merging**
